// Mock game cover colors (gradients) since we don't have real images
export const GENRE_COLORS = {
  Action: ['#ff4757', '#c0392b'],
  RPG: ['#9b59b6', '#6c3483'],
  Strategy: ['#2980b9', '#1a5276'],
  Puzzle: ['#f39c12', '#d68910'],
  Horror: ['#2c3e50', '#1a252f'],
  Adventure: ['#27ae60', '#1e8449'],
  Shooter: ['#e74c3c', '#922b21'],
  Simulation: ['#16a085', '#0e6655'],
  Sports: ['#f1c40f', '#d4ac0d'],
  Indie: ['#8e44ad', '#6c3483'],
};

export const GENRES = ['Action', 'RPG', 'Strategy', 'Puzzle', 'Horror', 'Adventure', 'Shooter', 'Simulation', 'Sports', 'Indie'];

export const mockGames = [
  {
    id: 1,
    title: 'Stellar Drift',
    genre: 'Action',
    price: 19.99,
    rating: 4.5,
    reviews: 342,
    description: 'A fast-paced space shooter with stunning visuals and an epic storyline. Fight through hordes of alien invaders across 20 unique planets.',
    developer: 'NovaStar Studios',
    releaseDate: '2024-03-15',
    tags: ['Space', 'Shooter', 'Sci-Fi', 'Singleplayer'],
    isNew: true,
    isFeatured: true,
    isFree: false,
    downloads: 15200,
    screenshots: 3,
  },
  {
    id: 2,
    title: 'Dungeon Chronicle',
    genre: 'RPG',
    price: 24.99,
    rating: 4.8,
    reviews: 891,
    description: 'Embark on an epic fantasy adventure with deep character customization, branching storylines, and strategic turn-based combat.',
    developer: 'IronForge Games',
    releaseDate: '2023-11-20',
    tags: ['Fantasy', 'RPG', 'Turn-Based', 'Story-Rich'],
    isNew: false,
    isFeatured: true,
    isFree: false,
    downloads: 48900,
    screenshots: 4,
  },
  {
    id: 3,
    title: 'CyberGrid',
    genre: 'Strategy',
    price: 14.99,
    rating: 4.2,
    reviews: 215,
    description: 'Build and manage your cyberpunk city in this detailed strategy simulation. Balance resources, manage citizens, and fend off corporate invasions.',
    developer: 'Nexus Interactive',
    releaseDate: '2024-01-08',
    tags: ['Cyberpunk', 'City-Builder', 'Strategy'],
    isNew: true,
    isFeatured: false,
    isFree: false,
    downloads: 9800,
    screenshots: 3,
  },
  {
    id: 4,
    title: 'Phantom Maze',
    genre: 'Puzzle',
    price: 0,
    rating: 4.6,
    reviews: 1240,
    description: 'Mind-bending puzzles in a hauntingly beautiful environment. Explore 100+ levels of increasing difficulty.',
    developer: 'Ghost Pixel',
    releaseDate: '2023-08-14',
    tags: ['Puzzle', 'Free-to-Play', 'Relaxing'],
    isNew: false,
    isFeatured: true,
    isFree: true,
    downloads: 125000,
    screenshots: 2,
  },
  {
    id: 5,
    title: 'Shadows of Dusk',
    genre: 'Horror',
    price: 12.99,
    rating: 4.4,
    reviews: 567,
    description: 'A psychological horror experience that will haunt your dreams. Survive the night in an abandoned mansion filled with unspeakable terrors.',
    developer: 'DarkRoom Dev',
    releaseDate: '2024-02-29',
    tags: ['Horror', 'Psychological', 'Survival', 'Atmospheric'],
    isNew: true,
    isFeatured: false,
    isFree: false,
    downloads: 31400,
    screenshots: 3,
  },
  {
    id: 6,
    title: 'Lost Horizon',
    genre: 'Adventure',
    price: 17.99,
    rating: 4.7,
    reviews: 423,
    description: 'An open-world adventure game set in a breathtaking alien world. Discover ancient ruins, forge alliances, and uncover the truth behind a galactic conspiracy.',
    developer: 'Horizon Craft',
    releaseDate: '2023-12-05',
    tags: ['Open-World', 'Exploration', 'Sci-Fi', 'Adventure'],
    isNew: false,
    isFeatured: true,
    isFree: false,
    downloads: 27600,
    screenshots: 4,
  },
  {
    id: 7,
    title: 'BulletStorm X',
    genre: 'Shooter',
    price: 29.99,
    rating: 4.1,
    reviews: 788,
    description: 'The ultimate tactical shooter experience. Team up with friends in 5v5 competitive matches or take on AI-driven missions.',
    developer: 'RapidFire Studios',
    releaseDate: '2024-04-01',
    tags: ['FPS', 'Multiplayer', 'Tactical', 'Competitive'],
    isNew: true,
    isFeatured: false,
    isFree: false,
    downloads: 62100,
    screenshots: 3,
  },
  {
    id: 8,
    title: 'Farm Chronicles',
    genre: 'Simulation',
    price: 9.99,
    rating: 4.3,
    reviews: 1890,
    description: 'Build the farm of your dreams in this cozy simulation game. Grow crops, raise animals, build relationships with villagers.',
    developer: 'Cozy Corner Dev',
    releaseDate: '2023-06-12',
    tags: ['Farming', 'Simulation', 'Cozy', 'Relaxing'],
    isNew: false,
    isFeatured: false,
    isFree: false,
    downloads: 94300,
    screenshots: 2,
  },
  {
    id: 9,
    title: 'Velocity Rush',
    genre: 'Sports',
    price: 19.99,
    rating: 4.0,
    reviews: 312,
    description: 'High-octane racing game with 50 tracks, 30 vehicles, and online multiplayer for up to 16 players.',
    developer: 'Turbo Games',
    releaseDate: '2024-01-22',
    tags: ['Racing', 'Sports', 'Multiplayer'],
    isNew: true,
    isFeatured: false,
    isFree: false,
    downloads: 18700,
    screenshots: 3,
  },
  {
    id: 10,
    title: 'PixelQuest',
    genre: 'Indie',
    price: 0,
    rating: 4.9,
    reviews: 2341,
    description: 'A love letter to classic 16-bit RPGs. Journey through a vast pixel-art world with a heartfelt story that will make you laugh and cry.',
    developer: 'LoFi Games',
    releaseDate: '2023-09-30',
    tags: ['Pixel-Art', 'Indie', 'RPG', 'Free-to-Play'],
    isNew: false,
    isFeatured: true,
    isFree: true,
    downloads: 210000,
    screenshots: 2,
  },
  {
    id: 11,
    title: 'Void Walker',
    genre: 'Action',
    price: 22.99,
    rating: 4.3,
    reviews: 445,
    description: 'Hack and slash your way through interdimensional chaos. Featuring 15 unique character classes and endless replayability.',
    developer: 'Warp Zone Studios',
    releaseDate: '2023-10-18',
    tags: ['Hack and Slash', 'Action', 'Rogue-like'],
    isNew: false,
    isFeatured: false,
    isFree: false,
    downloads: 35600,
    screenshots: 3,
  },
  {
    id: 12,
    title: 'Mythscape',
    genre: 'RPG',
    price: 34.99,
    rating: 4.6,
    reviews: 678,
    description: 'A massive online RPG with procedurally generated worlds, thousands of quests, and a living economy system.',
    developer: 'Epic Realm Games',
    releaseDate: '2024-03-28',
    tags: ['MMORPG', 'Open-World', 'Fantasy'],
    isNew: true,
    isFeatured: false,
    isFree: false,
    downloads: 41200,
    screenshots: 4,
  },
];

export const mockUsers = [
  { id: 1, name: 'Alex Morgan', email: 'alex@example.com', role: 'customer', avatar: null, joinDate: '2024-01-15', purchases: [1, 4, 6], cart: [] },
  { id: 2, name: 'Sam Chen', email: 'sam@example.com', role: 'developer', avatar: null, joinDate: '2023-11-08', studio: 'NovaStar Studios' },
  { id: 3, name: 'Admin User', email: 'admin@gamevault.com', role: 'admin', avatar: null, joinDate: '2023-01-01' },
];

export const mockReviews = [
  { id: 1, gameId: 1, userId: 1, userName: 'Alex Morgan', rating: 5, text: 'Absolutely incredible game! The space combat feels tight and responsive. Could play this for hours.', date: '2024-03-20', helpful: 42 },
  { id: 2, gameId: 1, userId: 4, userName: 'Jordan Kim', rating: 4, text: 'Great game overall. The story is engaging and the graphics are stunning. Minor performance issues on older hardware.', date: '2024-03-18', helpful: 28 },
  { id: 3, gameId: 2, userId: 1, userName: 'Alex Morgan', rating: 5, text: 'Best RPG I have played in years. The branching storylines are incredible and every choice matters.', date: '2024-01-10', helpful: 89 },
  { id: 4, gameId: 4, userId: 5, userName: 'Riley Stone', rating: 5, text: 'Free to play and still one of the best puzzle games out there. The devs really care about quality.', date: '2023-12-01', helpful: 156 },
];

export const mockOrders = [
  { id: 'ORD-001', userId: 1, gameId: 1, gameName: 'Stellar Drift', price: 19.99, date: '2024-03-15', status: 'completed', paymentMethod: 'Credit Card' },
  { id: 'ORD-002', userId: 1, gameId: 6, gameName: 'Lost Horizon', price: 17.99, date: '2024-02-20', status: 'completed', paymentMethod: 'PayPal' },
];

export const mockAdminStats = {
  totalUsers: 15420,
  totalGames: 248,
  totalRevenue: 284650,
  totalOrders: 38920,
  newUsersThisMonth: 1240,
  revenueThisMonth: 24800,
  activeGames: 231,
  pendingApprovals: 7,
};
